services:
  postgres:
    image: postgres:17
    container_name: pg
    environment:
      POSTGRES_USER: usr_api
      POSTGRES_PASSWORD: test
      POSTGRES_DB: api
    ports:
      - "5433:5432"
  #  volumes:
  #    - ./data:/var/lib/postgresql/data
