// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package harbordb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type HarborProject struct {
	ID         int32
	Name       string
	CustomerID string
	CreatedBy  string
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
}
