// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package harbordb

import (
	"context"
)

const insertHarborProject = `-- name: InsertHarborProject :exec
INSERT INTO harbor_projects (
    name,
    customer_id,
    created_by
) VALUES (
    $1, $2, $3
)
`

type InsertHarborProjectParams struct {
	Name       string
	CustomerID string
	CreatedBy  string
}

func (q *Queries) InsertHarborProject(ctx context.Context, arg InsertHarborProjectParams) error {
	_, err := q.db.Exec(ctx, insertHarborProject, arg.Name, arg.CustomerID, arg.CreatedBy)
	return err
}
