version: '3'
services:
  postgres:
    restart: unless-stopped
    image: postgres:15-alpine
    env_file: env/postgres.env
    volumes:
    - postgres-data:/var/lib/postgresql/data
    networks:
      - keycloak
  keycloak:
    restart: unless-stopped
    image: bitnami/keycloak:24
    depends_on:
      - "postgres"
    env_file:
      - env/keycloak.env
    networks:
      - keycloak
      - traefik_network
    labels:
      traefik.enable: true
      traefik.docker.network: rproxy_traefik_network
      traefik.http.routers.keycloak.entrypoints: web,websecure
      traefik.http.services.keycloak.loadbalancer.server.port: 8080
      traefik.http.routers.keycloak.rule: Host(`auth.scms.ovh`)
      traefik.http.routers.keycloak.tls: true
      traefik.http.routers.keycloak.tls.certresolver: leresolver
      traefik.http.routers.keycloak.middlewares: compresstraefik
      traefik.http.middlewares.compresstraefik.compress: true
    volumes:
      - keycloak-export:/opt/bitnami/keycloak/export
networks:
    keycloak:
    traefik_network:
      name: rproxy_traefik_network
      external: true

volumes:
  postgres-data: